-- Live bank feeds (Fiskil) and firm/user sign-up fields.
--
-- Everything here had been added to the schema and applied locally with
-- `prisma db push` but never captured as a migration, so `migrate deploy`
-- on staging produced a database without FeedSyncRun and without any of the
-- feed columns. Generated by diffing the seven earlier migrations against
-- schema.prisma; nothing hand-edited.

-- CreateEnum
CREATE TYPE "AuState" AS ENUM ('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT');

-- CreateEnum
CREATE TYPE "ProfessionalBody" AS ENUM ('CA_ANZ', 'CPA_AUSTRALIA', 'IPA', 'ATMA', 'TPB', 'NTAA', 'OTHER');

-- AlterEnum
ALTER TYPE "FeedConnectionStatus" ADD VALUE 'EXPIRED';

-- AlterTable
ALTER TABLE "BankAccount" ADD COLUMN     "feedConnectionId" TEXT,
ADD COLUMN     "feedLastSyncedAt" TIMESTAMP(3),
ADD COLUMN     "feedProductCategory" TEXT;

-- AlterTable
ALTER TABLE "BankFeedConnection" ADD COLUMN     "arrangementId" TEXT,
ADD COLUMN     "authSessionExpiresAt" TIMESTAMP(3),
ADD COLUMN     "authSessionId" TEXT,
ADD COLUMN     "consentedAt" TIMESTAMP(3),
ADD COLUMN     "expiresAt" TIMESTAMP(3),
ADD COLUMN     "institutionId" TEXT,
ADD COLUMN     "institutionName" TEXT,
ADD COLUMN     "revokedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "BankFeedRequest" ADD COLUMN     "connectionId" TEXT;

-- AlterTable
ALTER TABLE "BankTransaction" ADD COLUMN     "executionAt" TIMESTAMP(3),
ADD COLUMN     "externalId" TEXT,
ADD COLUMN     "feedCategory" TEXT,
ADD COLUMN     "feedCategoryConfidence" TEXT,
ADD COLUMN     "feedMerchantCode" TEXT,
ADD COLUMN     "feedRaw" JSONB,
ADD COLUMN     "feedSubcategory" TEXT,
ADD COLUMN     "postedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Client" ADD COLUMN     "feedEndUserId" TEXT;

-- AlterTable
ALTER TABLE "Firm" ADD COLUMN     "howHeard" TEXT,
ADD COLUMN     "state" "AuState";

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "phone" TEXT,
ADD COLUMN     "professionalBody" "ProfessionalBody",
ADD COLUMN     "professionalTitle" TEXT;

-- AlterTable
ALTER TABLE "WebhookEvent" ADD COLUMN     "error" TEXT,
ADD COLUMN     "externalConnectionId" TEXT,
ADD COLUMN     "externalUserId" TEXT,
ADD COLUMN     "payload" JSONB,
ADD COLUMN     "processedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "FeedSyncRun" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "connectionId" TEXT,
    "trigger" TEXT NOT NULL,
    "event" TEXT,
    "status" TEXT NOT NULL DEFAULT 'RUNNING',
    "pagesFetched" INTEGER NOT NULL DEFAULT 0,
    "rowsInserted" INTEGER NOT NULL DEFAULT 0,
    "rowsUpdated" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),

    CONSTRAINT "FeedSyncRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "FeedSyncRun_clientId_startedAt_idx" ON "FeedSyncRun"("clientId", "startedAt");

-- CreateIndex
CREATE INDEX "FeedSyncRun_connectionId_idx" ON "FeedSyncRun"("connectionId");

-- CreateIndex
CREATE INDEX "BankAccount_feedConnectionId_idx" ON "BankAccount"("feedConnectionId");

-- CreateIndex
CREATE UNIQUE INDEX "BankAccount_clientId_externalAccountId_key" ON "BankAccount"("clientId", "externalAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "BankFeedConnection_authSessionId_key" ON "BankFeedConnection"("authSessionId");

-- CreateIndex
CREATE INDEX "BankFeedConnection_status_idx" ON "BankFeedConnection"("status");

-- CreateIndex
CREATE UNIQUE INDEX "BankFeedConnection_provider_externalConnectionId_key" ON "BankFeedConnection"("provider", "externalConnectionId");

-- CreateIndex
CREATE INDEX "BankFeedRequest_connectionId_idx" ON "BankFeedRequest"("connectionId");

-- CreateIndex
CREATE UNIQUE INDEX "BankTransaction_bankAccountId_externalId_key" ON "BankTransaction"("bankAccountId", "externalId");

-- CreateIndex
CREATE UNIQUE INDEX "Client_feedEndUserId_key" ON "Client"("feedEndUserId");

-- CreateIndex
CREATE INDEX "WebhookEvent_processedAt_idx" ON "WebhookEvent"("processedAt");

-- AddForeignKey
ALTER TABLE "BankAccount" ADD CONSTRAINT "BankAccount_feedConnectionId_fkey" FOREIGN KEY ("feedConnectionId") REFERENCES "BankFeedConnection"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BankFeedRequest" ADD CONSTRAINT "BankFeedRequest_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "BankFeedConnection"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedSyncRun" ADD CONSTRAINT "FeedSyncRun_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FeedSyncRun" ADD CONSTRAINT "FeedSyncRun_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "BankFeedConnection"("id") ON DELETE SET NULL ON UPDATE CASCADE;

